server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:temperatures
    username: sa
    password: p
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true