spring:
  datasource:
    url: jdbc:h2:file:/data/demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=MySQL
    username: sa
    password: password
  jpa:
    generate-ddl: true
  h2:
    console:
      enabled: true